config/routes.rb
Rails.application.routes.draw do
  
  


  devise_for :users
devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  namespace :admin do
    root 'products#index'
    resources :services
    resources :projects
    resources :products
    resources :providers
    resources :entradas
    resources :users     
    resources :salidas
    get "/pagina-inicio", to: "home_page#index"
    get "/editar-galeria", to: "home_page#main_gallery"
    post "/post-galeria", to: "home_page#upload_photos_main_gallery"
    post "/delete-img", to: "home_page#delete_img"
    get "/reportes", to: "reports#index"
    post "/reports/save", to: "reports#save"
  end
  root 'welcome#index'
  resources :services
  resources :projects
  resources :products
  resources :providers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entrada.rb
class Entrada < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    has_many :imagens
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :gallery
  has_one_attached :img
end

app/models/imagen.rb
class Imagen < ApplicationRecord
  belongs_to :gallery
  has_one_attached :img, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :provider
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/salida.rb
class Salida < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::BaseController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
    @action = "Crear"
  end

  # GET /services/1/edit
  def edit
    @action = "Cuardar Cambios"
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to admin_services_path, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to admin_services_path, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to admin_services_path, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'home'
  def index
    @items = []
    
      @images = Imagen.where(gallery_id: 1)
      @images.each do |imge|
        puts imge.img.service_url
        item = {
          id: imge.id,
          url: imge.img.service_url,
          active: imge.active
        }
        @items.push(item)
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/salidas_helper.rb
module SalidasHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/services/_form.html.erb
<%= form_with(model: [:admin,service], local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Descripcion" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit @action, class: 'btn btn-raised btn-primary' %>
  </div>
<% end %>

app/views/admin/services/edit.html.erb
<%= render 'admin/partials/sidenav'%>
<div class="card">
        <div class="card-body padding-largo">
    
                <div class="row">
                        <h1>Editar Servicio</h1>
                </div>
                <div class="row">
                        <%= render 'form', service: @service %>
                </div>
                <div class="row">
                        <%= link_to 'Regresar', admin_services_path %>
                </div>
        </div>
    </div>
    

app/views/admin/services/index.html.erb
<%= render 'admin/partials/sidenav'%>
<div class="card">

<h1>Servicios</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <%if current_user.level == 2%>
        <td>
            <%= link_to edit_admin_service_path(service), class: "right" do %>
            <i class="material-icons red-color tippy" >edit</i>
            <% end %>
          
            <%= link_to admin_service_url(service), method: :delete, data: { confirm: '¿Estas seguro de eliminar?'}, class: "right" do %>
            <i class="material-icons red-color tippy" >delete</i>
            <% end %>
        </td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>


<a href="<%=new_admin_service_path%>" class="btn btn-primary bmd-btn-fab" style="position:fixed;bottom: 45px; right: 24px;">
    <i class="material-icons" style="padding: 15px !important">add</i>
  </a>
  

app/views/admin/services/new.html.erb
<%= render 'admin/partials/sidenav'%>
<div class="card">
        <div class="card-body padding-largo">
    
                <div class="row">
                        <h1>Agregar Servicio</h1>
                </div>
                <div class="row">
                        <%= render 'form', service: @service %>
                </div>
                <div class="row">
                        <%= link_to 'Regresar', admin_services_path %>
                </div>
        </div>
    </div>
    

app/views/admin/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>