config/routes.rb
Rails.application.routes.draw do
  
  


  devise_for :users
devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  namespace :admin do
    root 'products#index'
    resources :services
    resources :projects
    resources :products
    resources :providers
    resources :entradas
    resources :users     
    resources :salidas
    get "/pagina-inicio", to: "home_page#index"
    get "/editar-galeria", to: "home_page#main_gallery"
    post "/post-galeria", to: "home_page#upload_photos_main_gallery"
    post "/delete-img", to: "home_page#delete_img"
    get "/reportes", to: "reports#index"
    post "/reports/save", to: "reports#save"
  end
  root 'welcome#index'
  resources :services
  resources :projects
  resources :products
  resources :providers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entrada.rb
class Entrada < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    has_many :imagens
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :gallery
  has_one_attached :img
end

app/models/imagen.rb
class Imagen < ApplicationRecord
  belongs_to :gallery
  has_one_attached :img, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :provider
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/salida.rb
class Salida < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @action = "Crear"
  end

  # GET /projects/1/edit
  def edit
    @action = "Cuardar Cambios"
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to admin_projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to admin_products_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_path, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description,:aqr)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'home'
  def index
    @items = []
    
      @images = Imagen.where(gallery_id: 1)
      @images.each do |imge|
        puts imge.img.service_url
        item = {
          id: imge.id,
          url: imge.img.service_url,
          active: imge.active
        }
        @items.push(item)
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/salidas_helper.rb
module SalidasHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/projects/_form.html.erb
<%= form_with(model: [:admin,project], local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Nombre"%>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description , "Descripcion  "%>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :aqr, "Encargado" %>
    <%= form.text_field :aqr , class: "form-control" %>
  </div>
  <div class="form-group" style="margin-top:1.2em;">
    <%= form.submit @action, class: 'btn btn-raised btn-primary' %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<%= render 'admin/partials/sidenav'%>
<div class="card">
        <div class="card-body padding-largo">
    
                <div class="row">
                        <h1>Editar Proyecto</h1>
                </div>
                <div class="row">
                        <%= render 'form', project: @project %>
                </div>
                <div class="row">
                        <%= link_to 'Regresar', admin_projects_path %>
                </div>
        </div>
    </div>
    

app/views/admin/projects/index.html.erb
<%= render 'admin/partials/sidenav'%>
<div class="card">

<h1>Proyectos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <%if current_user.level == 2%>
        <td>
            <%= link_to edit_admin_project_path(project), class: "right" do %>
            <i class="material-icons red-color tippy" >edit</i>
            <% end %>
          
            <%= link_to admin_project_path(project), method: :delete, data: { confirm: '¿Estas seguro de eliminar?'}, class: "right" do %>
            <i class="material-icons red-color tippy" >delete</i>
            <% end %>
        </td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<a href="<%=new_admin_project_path%>" class="btn btn-primary bmd-btn-fab" style="position:fixed;bottom: 45px; right: 24px;">
    <i class="material-icons" style="padding: 15px !important">add</i>
  </a>

app/views/admin/projects/new.html.erb
<%= render 'admin/partials/sidenav'%>
<div class="card">
    <div class="card-body padding-largo">

            <div class="row">
                    <h1>Agregar Proyecto</h1>
            </div>
            <div class="row">
                    <%= render 'form', project: @project %>
            </div>
            <div class="row">
                    <%= link_to 'Regresar', admin_projects_path %>
            </div>
    </div>
</div>

app/views/admin/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description, "Descripcion" %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :art, "Encargado" %>
    <%= form.text_field :arq %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>