config/routes.rb
Rails.application.routes.draw do
  
  


  devise_for :users
devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  namespace :admin do
    root 'products#index'
    resources :services
    resources :projects
    resources :products
    resources :providers
    resources :entradas
    resources :users     
    resources :salidas
    get "/pagina-inicio", to: "home_page#index"
    get "/editar-galeria", to: "home_page#main_gallery"
    post "/post-galeria", to: "home_page#upload_photos_main_gallery"
    post "/delete-img", to: "home_page#delete_img"
    get "/reportes", to: "reports#index"
    post "/reports/save", to: "reports#save"
  end
  root 'welcome#index'
  resources :services
  resources :projects
  resources :products
  resources :providers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entrada.rb
class Entrada < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    has_many :imagens
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :gallery
  has_one_attached :img
end

app/models/imagen.rb
class Imagen < ApplicationRecord
  belongs_to :gallery
  has_one_attached :img, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :provider
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/salida.rb
class Salida < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/salidas_helper.rb
module SalidasHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/partials/_entradasalida.html.erb
<div id="mySidenav" class="sidenav">
    <a href="<%=admin_entradas_path%>" >Entradas</a>
    <a href="<%=admin_salidas_path%>" >Salidas</a>
  </div>

app/views/admin/partials/_sidenav.html.erb
<!-- 

<ul class="sidenav-custom" style="position: fixed !important;
top: 65px;
left: 0;
width: 350px;
height: 100%;
background-color: rgb(17, 0, 255) !important;">
    <li  style="list-style: none !important;
    padding: 20px">      
      <a href="<%=admin_products_path%>" style="color: white; text-decoration:none; font-size: 18px"><i class="material-icons">inbox</i>Catalogo de Productos</a>
    </li>

    <li  style="list-style: none !important;
    padding: 20px">      
        <a href="<%=admin_services_path%>" style="color: white; text-decoration:none; font-size: 18px"><i class="material-icons">inbox</i>Catalogo de Servicios</a>
    </li>

    <li  style="list-style: none !important;
    padding: 20px">      
        <a href="<%=admin_providers_path%>" style="color: white; text-decoration:none; font-size: 18px"><i class="material-icons">inbox</i>Catalogo de Proveedores</a>
    </li>

    <li  style="list-style: none !important;
    padding: 20px">  
        <a href="<%=admin_projects_path%>" style="color: white; text-decoration:none; font-size: 18px"><i class="material-icons">inbox</i>Catalogo de Proyectos</a>
    </li>
</ul> -->


<div id="mySidenav" class="sidenav">
    <a href="<%=admin_products_path%>" >Catalogo de Productos</a>
    <a href="<%=admin_services_path%>" >Catalogo de Servicios</a>
    <a href="<%=admin_providers_path%>" >Catalogo de Proveedores</a>
    <a href="<%=admin_projects_path%>" >Catalogo de Proyectos</a>
  </div>