config/routes.rb
Rails.application.routes.draw do
  
  


  devise_for :users
devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  namespace :admin do
    root 'products#index'
    resources :services
    resources :projects
    resources :products
    resources :providers
    resources :entradas
    resources :users     
    resources :salidas
    get "/pagina-inicio", to: "home_page#index"
    get "/editar-galeria", to: "home_page#main_gallery"
    post "/post-galeria", to: "home_page#upload_photos_main_gallery"
    post "/delete-img", to: "home_page#delete_img"
    get "/reportes", to: "reports#index"
    post "/reports/save", to: "reports#save"
  end
  root 'welcome#index'
  resources :services
  resources :projects
  resources :products
  resources :providers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entrada.rb
class Entrada < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    has_many :imagens
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :gallery
  has_one_attached :img
end

app/models/imagen.rb
class Imagen < ApplicationRecord
  belongs_to :gallery
  has_one_attached :img, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :provider
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/salida.rb
class Salida < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/entradas_controller.rb
class Admin::EntradasController < Admin::BaseController
  before_action :set_entrada, only: [:show, :edit, :update, :destroy]

  # GET /entradas
  # GET /entradas.json
  def index
    @entradas = Entrada.all
  end

  # GET /entradas/1
  # GET /entradas/1.json
  def show
  end

  # GET /entradas/new
  def new
    @entrada = Entrada.new
  end

  # GET /entradas/1/edit
  def edit
  end

  # POST /entradas
  # POST /entradas.json
  def create
    @entrada = Entrada.new(entrada_params)

    respond_to do |format|
      if @entrada.save
        format.html { redirect_to admin_entrada_path(@entrada), notice: 'Entrada was successfully created.' }
        format.json { render :show, status: :created, location: @entrada }
      else
        format.html { render :new }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entradas/1
  # PATCH/PUT /entradas/1.json
  def update
    respond_to do |format|
      if @entrada.update(entrada_params)
        format.html { redirect_to admin_entrada_path(@entrada), notice: 'Entrada was successfully updated.' }
        format.json { render :show, status: :ok, location: @entrada }
      else
        format.html { render :edit }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entradas/1
  # DELETE /entradas/1.json
  def destroy
    @entrada.destroy
    respond_to do |format|
      format.html { redirect_to admin_entradas_url, notice: 'Entrada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrada
      @entrada = Entrada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrada_params
      params.require(:entrada).permit(:name, :description, :price, :qty, :payment)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'home'
  def index
    @items = []
    
      @images = Imagen.where(gallery_id: 1)
      @images.each do |imge|
        puts imge.img.service_url
        item = {
          id: imge.id,
          url: imge.img.service_url,
          active: imge.active
        }
        @items.push(item)
      end
  end
end

app/helpers/admin/entradas_helper.rb
module Admin::EntradasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/salidas_helper.rb
module SalidasHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/entradas/_form.html.erb
<%= form_with(model: [:admin,@entrada], local: true) do |form| %>


  <div class="form-group">
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name , class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :description, "descripcion" %>
    <%= form.text_field :description, class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :price , "Precio"%>
    <%= form.text_field :price , class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :qty, "Cantidad" %>
    <%= form.text_field :qty , class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :payment, "Tipo de Pago"%>
    <%= form.text_field :payment , class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/entradas/edit.html.erb
<%= render 'admin/partials/entradasalida'%>

<div class="card">
        <div class="card-body padding-largo">
    
                <div class="row">
                        <h1>Agregar Entrada</h1>
                </div>
                <div class="row">
                        <%= render 'form', entrada: @entrada %>
                </div>
                <div class="row">
                        <%= link_to 'Regresar', admin_entradas_path %>
                </div>
        </div>
    </div>
    

app/views/admin/entradas/index.html.erb
<%= render 'admin/partials/entradasalida'%>
<div class="card">

    <h1>Entradas</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Descripcion</th>
          <th>Pago</th>
          <th>Precio</th>
          
          <th>Cantidad</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @entradas.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= product.payment %></td>
            <td><%= product.price %></td>  
            
            <td><%=product.qty%></td>
            <%if current_user.level == 2%>
            <td>
                <%= link_to edit_admin_entrada_path(product), class: "right" do %>
                <i class="material-icons red-color tippy" >edit</i>
                <% end %>
              
                <%= link_to admin_entrada_url(product), method: :delete, data: { confirm: '¿Estas seguro de eliminar?'}, class: "right" do %>
                <i class="material-icons red-color tippy" >delete</i>
                <% end %>
            </td>
            <%end%>
          </tr>
        <% end %>
      </tbody>
    </table>
    
</div>
<br>


<a href="<%=new_admin_salida_path%>" class="btn btn-primary bmd-btn-fab" style="position:fixed;bottom: 45px; right: 24px;">
  <i class="material-icons" style="padding: 15px !important">add</i>
</a>

app/views/admin/entradas/new.html.erb
<%= render 'admin/partials/entradasalida'%>

<div class="card">
        <div class="card-body padding-largo">
    
                <div class="row">
                        <h1>Agregar Entrada</h1>
                </div>
                <div class="row">
                        <%= render 'form', product: @entrada %>
                </div>
                <div class="row">
                        <%= link_to 'Regresar', admin_entradas_path %>
                </div>
        </div>
    </div>
    

app/views/admin/entradas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entrada.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @entrada.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @entrada.price %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @entrada.qty %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @entrada.payment %>
</p>

<%= link_to 'Edit', edit_entrada_path(@entrada) %> |
<%= link_to 'Back', entradas_path %>